# Welcome to Jekyll!
#

# Site settings
title: All Tech 
description: Suporte é a nossa praia!  
 
 
owner: isweluiz.com.br # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: isweluiz@hotmail.com
baseurl: "/portifolio" # the subpath of your site, e.g. /blog
url: "isweluiz..com.br/portifolio" # the base hostname & protocol for your site
social:
 # twitter: https://twitter.com/<username>
   github: https://github.com/isweluiz
   linkedin-square: https://linkedin.com/in/isweluiz
 # facebook-official: https://facebook.com/<username>
 # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: isweluiz@hotmail.com
  #flickr:
  instagram:isweluiz
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
